
/**
 * AUTO-GENERATED - DO NOT EDIT
 * This file is generated by the Supabase MCP server.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      books: {
        Row: {
          author: string
          available_copies: number
          category_id: string | null
          cover_url: string | null
          created_at: string
          description: string | null
          genre: string | null
          id: string
          rating: number | null
          summary: string | null
          title: string
          total_copies: number
          updated_at: string
        }
        Insert: {
          author: string
          available_copies?: number
          category_id?: string | null
          cover_url?: string | null
          created_at?: string
          description?: string | null
          genre?: string | null
          id?: string
          rating?: number | null
          summary?: string | null
          title: string
          total_copies?: number
          updated_at?: string
        }
        Update: {
          author?: string
          available_copies?: number
          category_id?: string | null
          cover_url?: string | null
          created_at?: string
          description?: string | null
          genre?: string | null
          id?: string
          rating?: number | null
          summary?: string | null
          title?: string
          total_copies?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "books_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      borrow_records: {
        Row: {
          book_id: string
          borrow_date: string
          created_at: string
          due_date: string
          id: string
          return_date: string | null
          status: Database["public"]["Enums"]["borrow_status"]
          updated_at: string
          user_id: string
        }
        Insert: {
          book_id: string
          borrow_date?: string
          created_at?: string
          due_date: string
          id?: string
          return_date?: string | null
          status?: Database["public"]["Enums"]["borrow_status"]
          updated_at?: string
          user_id: string
        }
        Update: {
          book_id?: string
          borrow_date?: string
          created_at?: string
          due_date?: string
          id?: string
          return_date?: string | null
          status?: Database["public"]["Enums"]["borrow_status"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "borrow_records_book_id_fkey"
            columns: ["book_id"]
            isOneToOne: false
            referencedRelation: "books"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "borrow_records_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      categories: {
        Row: {
          created_at: string
          description: string | null
          id: string
          name: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          name: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      fines: {
        Row: {
          amount: number
          borrow_record_id: string | null
          created_at: string
          id: string
          paid_date: string | null
          reason: string
          status: Database["public"]["Enums"]["fine_status"]
          updated_at: string
          user_id: string
        }
        Insert: {
          amount: number
          borrow_record_id?: string | null
          created_at?: string
          id?: string
          paid_date?: string | null
          reason?: string
          status?: Database["public"]["Enums"]["fine_status"]
          updated_at?: string
          user_id: string
        }
        Update: {
          amount?: number
          borrow_record_id?: string | null
          created_at?: string
          id?: string
          paid_date?: string | null
          reason?: string
          status?: Database["public"]["Enums"]["fine_status"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "fines_borrow_record_id_fkey"
            columns: ["borrow_record_id"]
            isOneToOne: false
            referencedRelation: "borrow_records"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fines_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          branch: string | null
          created_at: string
          email: string | null
          full_name: string | null
          id: string
          role: Database["public"]["Enums"]["user_role"]
          semester: number | null
          status: Database["public"]["Enums"]["user_status"]
          university_id: string | null
          updated_at: string
          year: number | null
        }
        Insert: {
          branch?: string | null
          created_at?: string
          email?: string | null
          full_name?: string | null
          id: string
          role?: Database["public"]["Enums"]["user_role"]
          semester?: number | null
          status?: Database["public"]["Enums"]["user_status"]
          university_id?: string | null
          updated_at?: string
          year?: number | null
        }
        Update: {
          branch?: string | null
          created_at?: string
          email?: string | null
          full_name?: string | null
          id?: string
          role?: Database["public"]["Enums"]["user_role"]
          semester?: number | null
          status?: Database["public"]["Enums"]["user_status"]
          university_id?: string | null
          updated_at?: string
          year?: number | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      is_admin: { Args: never; Returns: boolean }
    }
    Enums: {
      borrow_status: "BORROWED" | "RETURNED" | "OVERDUE"
      fine_status: "PENDING" | "PAID" | "WAIVED"
      user_role: "ADMIN" | "STUDENT" | "LIBRARIAN" | "FACULTY"
      user_status: "PENDING" | "APPROVED" | "REJECTED"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
